version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 80:8000
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=b6392ffe53fb66510cc9
      - DRONE_GITHUB_SECRET=b5ea660d95d47efc7874017a79bb31c4861d8127
      - DRONE_SECRET=xppdrontest

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=xppdrontest
